export const ESPN_TO_NO: Record<string, string> = {
  'France': 'Frankrike',
  'Spain': 'Spania',
  'England': 'England',
  'Brazil': 'Brasil',
  'Argentina': 'Argentina',
  'Portugal': 'Portugal',
  'Germany': 'Tyskland',
  'Netherlands': 'Nederland',
  'Norway': 'Norge',
  'Belgium': 'Belgia',
  'United States': 'USA',
  'Colombia': 'Colombia',
  'Uruguay': 'Uruguay',
  'Morocco': 'Marokko',
  'Japan': 'Japan',
  'Mexico': 'Mexico',
  'Sweden': 'Sverige',
  'Croatia': 'Kroatia',
  'Switzerland': 'Sveits',
  'Ecuador': 'Ecuador',
  'Senegal': 'Senegal',
  'Turkey': 'Tyrkia',
  'Türkiye': 'Tyrkia',
  'Austria': 'Østerrike',
  'Canada': 'Canada',
  'Paraguay': 'Paraguay',
  'Algeria': 'Algerie',
  'Czech Republic': 'Tsjekkia',
  'Czechia': 'Tsjekkia',
  "Cote d'Ivoire": 'Elfenbenskysten',
  "Côte d'Ivoire": 'Elfenbenskysten',
  'South Korea': 'Sør-Korea',
  'Korea Republic': 'Sør-Korea',
  'Egypt': 'Egypt',
  'Scotland': 'Skottland',
  'Ghana': 'Ghana',
  'Bosnia and Herzegovina': 'Bosnia-Hercegovina',
  'Bosnia-Herzegovina': 'Bosnia-Hercegovina',
  'Iran': 'Iran',
  'Australia': 'Australia',
  'Tunisia': 'Tunisia',
  'DR Congo': 'Congo DR',
  'Democratic Republic of Congo': 'Congo DR',
  'Saudi Arabia': 'Saudi-Arabia',
  'New Zealand': 'New Zealand',
  'Qatar': 'Qatar',
  'Iraq': 'Irak',
  'Jordan': 'Jordan',
  'Cape Verde': 'Kapp Verde',
  'Cape Verde Islands': 'Kapp Verde',
  'Cape Verde Island': 'Kapp Verde',
  'Uzbekistan': 'Usbekistan',
  'Panama': 'Panama',
  'South Africa': 'Sør-Afrika',
  'Curaçao': 'Curaçao',
  'Haiti': 'Haiti',
}
